const plants: Flora[] = [
  {
    commonName: "Sweet Flag",
    scientificName: "Acorus calamus",
    localNames: ["Vacha", "Bach", "Calamus"],
    plantFamily: "Acoraceae",
    pollinators: ["Bees", "Flies"],
    companionPlants: [],
    type: "Herbs",
    toxicity: {
      toxic: true,
      conditions:
        "Can be toxic if ingested in large amounts due to the presence of beta-asarone.",
    },
    medicinalProperties:
      "Used in traditional medicine for digestive issues, respiratory problems, and as a sedative.",
    states: [
      "Andhra Pradesh",
      "Assam",
      "Bihar",
      "Karnataka",
      "Kerala",
      "Madhya Pradesh",
      "Maharashtra",
      "Odisha",
      "Tamil Nadu",
      "Uttar Pradesh",
      "West Bengal",
    ],
    climate: ["Sunny", "Rainy", "Humid", "Warm", "Cool"],
    wateringFrequency: "Twice a week",
    fertilizer: ["Compost", "Manure"],
    identification:
      "Acorus calamus is a perennial herb with tall, erect leaves and a distinctive, sweet aroma.",
    soil: ["Loam", "Peat", "Moist soil", "Well-drained soil"],
    eatableParts: ["Root", "Rhizome"],
    sowingMethod: ["Direct seeding", "Transplanting", "Root division"],
    growthPeriod: ["Perennial"],
    pests: ["Aphids", "Spider mites"],
    humidity: ["High humidity", "Moist air"],
    temperature: ["Moderate", "Warm"],
    usage: [
      "Medicinal",
      "Aromatic",
      "Ornamental",
      "Culinary",
      "Soil improvement",
      "Erosion control",
      "Essential oil production",
    ],
  },
  {
    commonName: "Japanese Sweet Flag",
    scientificName: "Acorus gramineus",
    localNames: ["Japanese Rush", "Grass-leaf Sweet Flag"],
    plantFamily: "Acoraceae",
    pollinators: ["Bees", "Flies"],
    companionPlants: [],
    type: "Herbs",
    toxicity: {
      toxic: false,
      conditions: "",
    },
    medicinalProperties:
      "Used in traditional medicine for digestive and respiratory issues.",
    states: [
      "Andhra Pradesh",
      "Assam",
      "Bihar",
      "Karnataka",
      "Kerala",
      "Madhya Pradesh",
      "Maharashtra",
      "Odisha",
      "Tamil Nadu",
      "Uttar Pradesh",
      "West Bengal",
    ],
    climate: ["Sunny", "Humid", "Warm", "Cool"],
    wateringFrequency: "Twice a week",
    fertilizer: ["Compost", "Manure"],
    identification:
      "Acorus gramineus is a perennial herb with slender, grass-like leaves and a sweet aroma.",
    soil: ["Loam", "Peat", "Moist soil", "Well-drained soil"],
    eatableParts: ["Root", "Rhizome"],
    sowingMethod: ["Direct seeding", "Transplanting", "Root division"],
    growthPeriod: ["Perennial"],
    pests: ["Aphids", "Spider mites"],
    humidity: ["High humidity", "Moist air"],
    temperature: ["Moderate", "Warm"],
    usage: [
      "Medicinal",
      "Ornamental",
      "Aromatic",
      "Soil improvement",
      "Erosion control",
    ],
  },
  {
    commonName: "Variegated Japanese Sweet Flag",
    scientificName: "Acorus gramineus 'Variegatus'",
    localNames: ["Variegated Japanese Rush"],
    plantFamily: "Acoraceae",
    pollinators: ["Bees", "Flies"],
    companionPlants: [],
    type: "Herbs",
    toxicity: {
      toxic: false,
      conditions: "",
    },
    medicinalProperties:
      "Used in traditional medicine for digestive and respiratory issues.",
    states: [
      "Andhra Pradesh",
      "Assam",
      "Bihar",
      "Karnataka",
      "Kerala",
      "Madhya Pradesh",
      "Maharashtra",
      "Odisha",
      "Tamil Nadu",
      "Uttar Pradesh",
      "West Bengal",
    ],
    climate: ["Sunny", "Humid", "Warm", "Cool"],
    wateringFrequency: "Twice a week",
    fertilizer: ["Compost", "Manure"],
    identification:
      "Acorus gramineus 'Variegatus' is a perennial herb with variegated, grass-like leaves and a sweet aroma.",
    soil: ["Loam", "Peat", "Moist soil", "Well-drained soil"],
    eatableParts: ["Root", "Rhizome"],
    sowingMethod: ["Direct seeding", "Transplanting", "Root division"],
    growthPeriod: ["Perennial"],
    pests: ["Aphids", "Spider mites"],
    humidity: ["High humidity", "Moist air"],
    temperature: ["Moderate", "Warm"],
    usage: ["Ornamental", "Aromatic", "Soil improvement", "Erosion control"],
  },
  {
    commonName: "Snap Ginger",
    scientificName: "Alpinia calcarata",
    localNames: ["Chitharathai", "Snap Ginger"],
    plantFamily: "Zingiberaceae",
    pollinators: ["Bees", "Butterflies"],
    companionPlants: [],
    type: "Herbs",
    toxicity: {
      toxic: false,
      conditions: "",
    },
    medicinalProperties:
      "Used in traditional medicine for anti-inflammatory, antimicrobial, and digestive aid properties.",
    states: [
      "Andhra Pradesh",
      "Assam",
      "Bihar",
      "Karnataka",
      "Kerala",
      "Madhya Pradesh",
      "Maharashtra",
      "Odisha",
      "Tamil Nadu",
      "Uttar Pradesh",
      "West Bengal",
    ],
    climate: ["Sunny", "Rainy", "Humid", "Warm"],
    wateringFrequency: "Twice a week",
    fertilizer: ["Compost", "Manure"],
    identification:
      "Alpinia calcarata is a perennial herb with tall, lance-shaped leaves and attractive white flowers with red streaks.",
    soil: ["Loam", "Peat", "Moist soil", "Well-drained soil"],
    eatableParts: ["Rhizome"],
    sowingMethod: ["Direct seeding", "Transplanting", "Root division"],
    growthPeriod: ["Perennial"],
    pests: ["Aphids", "Spider mites"],
    humidity: ["High humidity", "Moist air"],
    temperature: ["Warm", "Hot"],
    usage: ["Medicinal", "Ornamental", "Aromatic"],
  },
  {
    commonName: "Dwarf Bamboo",
    scientificName: "Arundinaria pumila",
    localNames: ["Dwarf Bamboo"],
    plantFamily: "Poaceae",
    pollinators: ["Wind"],
    companionPlants: [],
    type: "Grasses",
    toxicity: {
      toxic: false,
      conditions: "",
    },
    medicinalProperties:
      "Traditionally used for its anti-inflammatory properties.",
    states: [
      "Andhra Pradesh",
      "Assam",
      "Bihar",
      "Karnataka",
      "Kerala",
      "Madhya Pradesh",
      "Maharashtra",
      "Odisha",
      "Tamil Nadu",
      "Uttar Pradesh",
      "West Bengal",
    ],
    climate: ["Sunny", "Humid", "Warm"],
    wateringFrequency: "Weekly",
    fertilizer: ["Compost", "Manure"],
    identification:
      "Arundinaria pumila is a small, clumping bamboo with slender, green stems and narrow leaves.",
    soil: ["Loam", "Sandy loam", "Moist soil", "Well-drained soil"],
    eatableParts: ["Shoot"],
    sowingMethod: ["Direct seeding", "Transplanting", "Root division"],
    growthPeriod: ["Perennial"],
    pests: ["Aphids", "Spider mites"],
    humidity: ["High humidity", "Moist air"],
    temperature: ["Moderate", "Warm"],
    usage: [
      "Ornamental",
      "Soil improvement",
      "Erosion control",
      "Privacy screen",
      "Windbreak",
    ],
  },

  {
    commonName: "Giant Reed",
    scientificName: "Arundo donax",
    localNames: ["Carrizo", "Spanish Cane"],
    plantFamily: "Poaceae",
    pollinators: ["Wind"],
    companionPlants: [],
    type: "Grasses",
    toxicity: {
      toxic: false,
      conditions: "",
    },
    medicinalProperties:
      "Used in traditional medicine for its anti-inflammatory and diuretic properties.",
    states: [
      "Andhra Pradesh",
      "Assam",
      "Bihar",
      "Karnataka",
      "Kerala",
      "Madhya Pradesh",
      "Maharashtra",
      "Odisha",
      "Tamil Nadu",
      "Uttar Pradesh",
      "West Bengal",
    ],
    climate: ["Sunny", "Warm", "Humid"],
    wateringFrequency: "Weekly",
    fertilizer: ["Compost", "Manure"],
    identification:
      "Arundo donax is a tall, perennial grass with thick stems and long, flat leaves.",
    soil: ["Loam", "Sandy loam", "Moist soil", "Well-drained soil"],
    eatableParts: ["Shoot"],
    sowingMethod: ["Direct seeding", "Transplanting", "Root division"],
    growthPeriod: ["Perennial"],
    pests: ["Aphids", "Spider mites"],
    humidity: ["High humidity", "Moist air"],
    temperature: ["Warm", "Hot"],
    usage: [
      "Ornamental",
      "Soil improvement",
      "Erosion control",
      "Biofuel",
      "Windbreak",
    ],
  },
  {
    commonName: "Variegated Giant Reed",
    scientificName: "Arundo donax 'Versicolor'",
    localNames: ["Variegated Carrizo", "Variegated Spanish Cane"],
    plantFamily: "Poaceae",
    pollinators: ["Wind"],
    companionPlants: [],
    type: "Grasses",
    toxicity: {
      toxic: false,
      conditions: "",
    },
    medicinalProperties:
      "Used in traditional medicine for its anti-inflammatory and diuretic properties.",
    states: [
      "Andhra Pradesh",
      "Assam",
      "Bihar",
      "Karnataka",
      "Kerala",
      "Madhya Pradesh",
      "Maharashtra",
      "Odisha",
      "Tamil Nadu",
      "Uttar Pradesh",
      "West Bengal",
    ],
    climate: ["Sunny", "Warm", "Humid"],
    wateringFrequency: "Weekly",
    fertilizer: ["Compost", "Manure"],
    identification:
      "Arundo donax 'Versicolor' is a tall, perennial grass with variegated leaves that have white and green stripes.",
    soil: ["Loam", "Sandy loam", "Moist soil", "Well-drained soil"],
    eatableParts: ["Shoot"],
    sowingMethod: ["Direct seeding", "Transplanting", "Root division"],
    growthPeriod: ["Perennial"],
    pests: ["Aphids", "Spider mites"],
    humidity: ["High humidity", "Moist air"],
    temperature: ["Warm", "Hot"],
    usage: [
      "Ornamental",
      "Soil improvement",
      "Erosion control",
      "Biofuel",
      "Windbreak",
    ],
  },
  {
    commonName: "Timor Black Bamboo",
    scientificName: "Bambusa lako",
    localNames: ["Timor Black Bamboo"],
    plantFamily: "Poaceae",
    pollinators: ["Wind"],
    companionPlants: [],
    type: "Grasses",
    toxicity: {
      toxic: false,
      conditions: "",
    },
    medicinalProperties: "Not commonly used in traditional medicine.",
    states: [
      "Andhra Pradesh",
      "Assam",
      "Bihar",
      "Karnataka",
      "Kerala",
      "Madhya Pradesh",
      "Maharashtra",
      "Odisha",
      "Tamil Nadu",
      "Uttar Pradesh",
      "West Bengal",
    ],
    climate: ["Sunny", "Warm", "Humid"],
    wateringFrequency: "Weekly",
    fertilizer: ["Compost", "Manure"],
    identification:
      "Bambusa lako is a medium-sized bamboo with glossy, black culms and green leaves.",
    soil: ["Loam", "Sandy loam", "Moist soil", "Well-drained soil"],
    eatableParts: ["Shoot"],
    sowingMethod: ["Direct seeding", "Transplanting", "Root division"],
    growthPeriod: ["Perennial"],
    pests: ["Aphids", "Spider mites"],
    humidity: ["High humidity", "Moist air"],
    temperature: ["Warm", "Hot"],
    usage: [
      "Ornamental",
      "Soil improvement",
      "Erosion control",
      "Privacy screen",
      "Windbreak",
      "Timber production",
    ],
  },
  {
    commonName: "Hedge Bamboo",
    scientificName: "Bambusa multiplex",
    localNames: ["Chinese Hedge Bamboo", "Clumping Bamboo"],
    plantFamily: "Poaceae",
    pollinators: ["Wind"],
    companionPlants: [],
    type: "Grasses",
    toxicity: {
      toxic: false,
      conditions: "",
    },
    medicinalProperties: "Not commonly used in traditional medicine.",
    states: [
      "Andhra Pradesh",
      "Assam",
      "Bihar",
      "Karnataka",
      "Kerala",
      "Madhya Pradesh",
      "Maharashtra",
      "Odisha",
      "Tamil Nadu",
      "Uttar Pradesh",
      "West Bengal",
    ],
    climate: ["Sunny", "Warm", "Humid"],
    wateringFrequency: "Weekly",
    fertilizer: ["Compost", "Manure"],
    identification:
      "Bambusa multiplex is a clumping bamboo with dense foliage and multiple stems arising from the base.",
    soil: ["Loam", "Sandy loam", "Moist soil", "Well-drained soil"],
    eatableParts: ["Shoot"],
    sowingMethod: ["Direct seeding", "Transplanting", "Root division"],
    growthPeriod: ["Perennial"],
    pests: ["Aphids", "Spider mites"],
    humidity: ["High humidity", "Moist air"],
    temperature: ["Warm", "Hot"],
    usage: [
      "Ornamental",
      "Soil improvement",
      "Erosion control",
      "Privacy screen",
      "Windbreak",
    ],
  },
];
