type PlantsFamily =
  | "Acanthaceae"
  | "Amaranthaceae"
  | "Anacardiaceae"
  | "Apiaceae"
  | "Apocynaceae"
  | "Araceae"
  | "Araliaceae"
  | "Arecaceae"
  | "Asclepiadaceae"
  | "Asteraceae"
  | "Balsaminaceae"
  | "Berberidaceae"
  | "Bignoniaceae"
  | "Boraginaceae"
  | "Brassicaceae"
  | "Cactaceae"
  | "Campanulaceae"
  | "Cannabaceae"
  | "Caprifoliaceae"
  | "Caryophyllaceae"
  | "Celastraceae"
  | "Chenopodiaceae"
  | "Clusiaceae"
  | "Convolvulaceae"
  | "Cucurbitaceae"
  | "Cyperaceae"
  | "Dioscoreaceae"
  | "Ebenaceae"
  | "Euphorbiaceae"
  | "Fabaceae"
  | "Fagaceae"
  | "Gentianaceae"
  | "Geraniaceae"
  | "Lamiaceae"
  | "Lauraceae"
  | "Liliaceae"
  | "Lythraceae"
  | "Malvaceae"
  | "Melastomataceae"
  | "Mimosaceae"
  | "Moraceae"
  | "Moringaceae"
  | "Musaceae"
  | "Myrtaceae"
  | "Oleaceae"
  | "Orchidaceae"
  | "Oxalidaceae"
  | "Papaveraceae"
  | "Passifloraceae"
  | "Pedaliaceae"
  | "Phyllanthaceae"
  | "Piperaceae"
  | "Plantaginaceae"
  | "Poaceae"
  | "Polygonaceae"
  | "Portulacaceae"
  | "Primulaceae"
  | "Ranunculaceae"
  | "Rosaceae"
  | "Rubiaceae"
  | "Rutaceae"
  | "Salicaceae"
  | "Sapindaceae"
  | "Sapotaceae"
  | "Solanaceae"
  | "Tiliaceae"
  | "Typhaceae"
  | "Urticaceae"
  | "Verbenaceae"
  | "Violaceae"
  | "Zingiberaceae";

type Pollinator =
  | "Bees"
  | "Butterflies"
  | "Moths"
  | "Flies"
  | "Birds"
  | "Beetles"
  | "Wasps"
  | "Bats"
  | "Wind";

type PlantType =
  | "Trees"
  | "Shrubs"
  | "Herbs"
  | "Grasses"
  | "Ferns"
  | "Mosses"
  | "Algae"
  | "Lichens"
  | "Epiphytes"
  | "Cacti and Succulents";

type SowingMethod =
  | "Direct seeding"
  | "Transplanting"
  | "Broadcast seeding"
  | "Drilling"
  | "Hill dropping"
  | "Seedling trays"
  | "Seed tape"
  | "Seed balls"
  | "Seedling plugs"
  | "Dibbling"
  | "Furrow planting"
  | "Ridge planting"
  | "Basin planting"
  | "Container planting"
  | "Layering"
  | "Root division"
  | "Cuttings"
  | "Grafting"
  | "Layering"
  | "Air layering";

type IndianState =
  | "Andhra Pradesh"
  | "Arunachal Pradesh"
  | "Assam"
  | "Bihar"
  | "Chhattisgarh"
  | "Goa"
  | "Gujarat"
  | "Haryana"
  | "Himachal Pradesh"
  | "Jharkhand"
  | "Karnataka"
  | "Kerala"
  | "Madhya Pradesh"
  | "Maharashtra"
  | "Manipur"
  | "Meghalaya"
  | "Mizoram"
  | "Nagaland"
  | "Odisha"
  | "Punjab"
  | "Rajasthan"
  | "Sikkim"
  | "Tamil Nadu"
  | "Telangana"
  | "Tripura"
  | "Uttar Pradesh"
  | "Uttarakhand"
  | "West Bengal";

type ClimateCondition =
  | "Sunny"
  | "Rainy"
  | "Cloudy"
  | "Foggy"
  | "Snowy"
  | "Windy"
  | "Stormy"
  | "Hailstorm"
  | "Tornado"
  | "Hurricane"
  | "Thunderstorm"
  | "Dry"
  | "Humid"
  | "Hot"
  | "Cold"
  | "Mild"
  | "Freezing"
  | "Warm"
  | "Cool"
  | "Temperate";

type WateringFrequency =
  | "Daily"
  | "Every other day"
  | "Twice a week"
  | "Weekly"
  | "Biweekly"
  | "Monthly"
  | "Varies";

type OrganicFertilizer =
  | "Compost"
  | "Manure"
  | "Bone Meal"
  | "Fish Emulsion"
  | "Blood Meal"
  | "Seaweed Extract";

type NonOrganicFertilizer =
  | "NPK Fertilizer"
  | "Urea"
  | "Ammonium Nitrate"
  | "Potassium Chloride"
  | "Superphosphate";

type Fertilizer = OrganicFertilizer | NonOrganicFertilizer;

type SoilType =
  | "Clay"
  | "Silt"
  | "Sand"
  | "Loam"
  | "Peat"
  | "Chalk"
  | "Limestone"
  | "Rocky"
  | "Sandy loam"
  | "Clay loam"
  | "Silt loam"
  | "Peat soil"
  | "Well-drained soil"
  | "Moist soil"
  | "Poorly-drained soil"
  | "Acidic soil"
  | "Neutral soil"
  | "Alkaline soil";

type EatablePart =
  | "Fruit"
  | "Seed"
  | "Leaf"
  | "Root"
  | "Stem"
  | "Flower"
  | "Bulb"
  | "Tuber"
  | "Shoot"
  | "Petal"
  | "Stalk"
  | "Rhizome"
  | "Corm"
  | "Pod"
  | "Nut"
  | "Berry"
  | "Pulp"
  | "Sap"
  | "Nectar"
  | "Honey"
  | "Leaves and stems"
  | "Leaves and flowers"
  | "Leaves and seeds"
  | "Whole plant"
  | "Other";

type GrowthPeriod =
  | "Annual"
  | "Biennial"
  | "Perennial"
  | "Short-lived perennial"
  | "Summer annual"
  | "Winter annual"
  | "Cool-season annual"
  | "Warm-season annual"
  | "Cool-season perennial"
  | "Warm-season perennial"
  | "Vegetative growth"
  | "Reproductive growth"
  | "Seedling growth"
  | "Early growth"
  | "Late growth"
  | "Rapid growth"
  | "Slow growth"
  | "Continuous growth"
  | "Dormant growth"
  | "Indeterminate growth"
  | "Determinant growth";

type Pest =
  | "Aphids"
  | "Whiteflies"
  | "Thrips"
  | "Spider mites"
  | "Mealybugs"
  | "Caterpillars"
  | "Leaf miners"
  | "Scale insects"
  | "Flea beetles"
  | "Japanese beetles"
  | "Earwigs"
  | "Slugs"
  | "Snails"
  | "Wireworms"
  | "Cutworms"
  | "Garden webworms"
  | "Armyworms"
  | "Corn earworms"
  | "Stink bugs"
  | "Leafhoppers"
  | "Fruit flies"
  | "Ants"
  | "Mosquitoes"
  | "Ticks"
  | "Termites"
  | "Bed bugs"
  | "Cockroaches"
  | "Fleas"
  | "Houseflies"
  | "Mosquitoes"
  | "Moths"
  | "Weevils"
  | "Borers"
  | "Sawflies"
  | "Nematodes";

type HumidityCondition =
  | "Low humidity"
  | "Moderate humidity"
  | "High humidity"
  | "Very high humidity"
  | "Dry air"
  | "Moist air"
  | "Humid air"
  | "Arid climate"
  | "Semi-arid climate"
  | "Tropical climate"
  | "Subtropical climate"
  | "Temperate climate"
  | "Polar climate";

type TemperatureCondition =
  | "Freezing"
  | "Very cold"
  | "Cold"
  | "Cool"
  | "Moderate"
  | "Warm"
  | "Hot"
  | "Very hot"
  | "Extreme heat"
  | "Tropical"
  | "Subtropical"
  | "Desert"
  | "Arctic"
  | "Polar";

type PlantUsage =
  | "Medicinal"
  | "Edible"
  | "Ornamental"
  | "Aromatic"
  | "Culinary"
  | "Industrial"
  | "Horticultural"
  | "Environmental"
  | "Bioremediation"
  | "Soil improvement"
  | "Erosion control"
  | "Wildlife habitat"
  | "Aesthetic"
  | "Fiber production"
  | "Timber production"
  | "Biofuel"
  | "Pollinator attractor"
  | "Companion planting"
  | "Groundcover"
  | "Shade provider"
  | "Windbreak"
  | "Privacy screen"
  | "Water retention"
  | "Natural dye"
  | "Essential oil production"
  | "Fodder"
  | "Mulch"
  | "Herbal tea"
  | "Fruit production"
  | "Vegetable production"
  | "Nut production"
  | "Seed production";

type Flora = {
  commonName: string;
  scientificName: string;
  localNames: string[];
  plantFamily: PlantsFamily;
  pollinators: Pollinator[];
  companionPlants: Flora[];
  type: PlantType;
  toxicity: { toxic: boolean; conditions: string };
  medicinalProperties: string;
  states: IndianState[];
  climate: ClimateCondition[];
  wateringFrequency: WateringFrequency;
  fertilizer: Fertilizer[];
  identification: string;
  soil: SoilType[];
  eatableParts: EatablePart[];
  sowingMethod: SowingMethod[];
  growthPeriod: GrowthPeriod[];
  pests: Pest[];
  humidity: HumidityCondition[];
  temperature: TemperatureCondition[];
  usage: PlantUsage[];
};
